### ISSUE TITLE
Thank you for your contribution! But I couldn't find the embedding code for the autoencoder mentioned in the paper.

### ISSUE THREAD

**Issue by yandong667** [lpworld/PURS#4]
Thank you very much for your contribution! 
  I have a couple of little questions, the first one is the embedding of autoencoder mentioned in your paper has not been found in the code, are they hidden elsewhere, or do I need to provide for them?
  The second is that after I ran the test.CSV dataset provided by you, the hit rate of the test was a little low, around 0.1. Is this normal?

**Comment by lpworld** [comment]
Hi, thanks for the questions.

(1) Yeah I didn't provide the autoencoder-embedding module in the code. The reason for that is because some datasets do not contain explicit user and item features. Therefore the embeddings cannot be generated through the autoencoder model; instead, they can be initialized and learned from user/item ids, as shown in the code. You can of course learn user/item embeddings using autoencoders separately and incorporate them into the model.

(2) No, it is not normal. The test.csv is only to show the structure of the dataset (I randomly select several records from the Youku dataset) as I cannot share the entire dataset with you. The complete dataset has a hit rate of ~0.7 as reported in the paper. You can also use the other two public datasets.

Best,
Pan

**Comment by yandong667** [comment]
Your reply perfectly solved my problem. Thank you very much!
